server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://C:/Users/Heather/Git/SpringCloudConfig
          #uri: https://github.com/hstandring/SpringCloudConfigRepo.git
      #label: develop